#!/usr/bin/env bash
#Web servers are the piece of software generating and serving HTML pages!
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo touch /var/www/html/index.html
sudo sh -c "echo Hello World! > /var/www/html/index.html"
sudo service nginx start
