#!/usr/bin/env bash
# A script to configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
REDIRECT="\\\tif (\$request_filename ~ redirect_me)\
	{\n\t\trewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;\n\t}"

sudo sed -i "/server_name _;/a $REDIRECT" /etc/nginx/sites-enabled/default

service nginx restart
