#!/usr/bin/env bash
# Install the load balancer
sudo apt-get update
sudo apt-get install haproxy -y
sudo sed -i "s/mode\thttp/mode\ttcp/" /etc/haproxy/haproxy.cfg
sudo sed -i "s/option\thttplog/option\ttcplog/" /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" >> /etc/default/haproxy

echo "" >> /etc/haproxy/haproxy.cfg

FRONTEND="frontend www\
\n\tbind *:80\
\n\tdefault_backend nginx_pool\n"

BACKEND="backend nginx_pool\
\n\tbalance roundrobin\
\n\tmode tcp\
\n\tserver web-01 3.236.4.92:80 check\
\n\tserver web-023.239.83.251:80 check\n"

sudo echo -e "$FRONTEND" >> /etc/haproxy/haproxy.cfg
sudo echo -e "$BACKEND" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart

